---
- name: Ansible for Kubuntu 25.10
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.13
    managed_apt_packages:
      # System essentials
      - ansible
      - ansible-lint
      - init
      - bash
      - linux-generic
      - ubuntu-minimal
      - ubuntu-standard
      - kubuntu-desktop
      # Localization
      - language-pack-en-base
      - language-pack-en
      # CLI tools
      - wget
      - tree
      - fastfetch
      - ca-certificates
      - curl
      - git
      - yt-dlp
      - gpg
      - pipx
      - openssh-server
      # Development
      - maven
      - postgresql-client-17
      - software-properties-common
      - apt-transport-https
      # Desktop applications
      - vlc
      - mpv
      - gource
      - syncthing
      - qdirstat
      - gimp
      - okular
      - kdeconnect
      # Flatpak support
      - flatpak
      - plasma-discover-backend-flatpak
      - kde-config-flatpak
      # Drivers and fonts
      - nvidia-driver-580
      - fonts-jetbrains-mono
      - qml-module-org-kde-notifications
      # Third-party repositories
      - tailscale
      - brave-browser
      - code
      - 1password
      - 1password-cli
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - warp-terminal
    managed_flatpaks:
      - md.obsidian.Obsidian
      - org.getoutline.OutlineManager
      - com.system76.Popsicle
      - net.ankiweb.Anki
      - org.zulip.Zulip
    # APT packages that should NOT be removed (essential system packages)
    protected_apt_packages:
      # Package management and system foundations
      - apt
      - dpkg
      - base-files
      - base-passwd
      - debconf
      - adduser
      # Init system and boot
      - systemd
      - systemd-sysv
      - init
      - initramfs-tools
      - plymouth
      # Shells and core utilities
      - bash
      - dash
      - coreutils
      - util-linux
      - perl-base
      # User authentication and security
      - login
      - passwd
      - sudo
      - keyutils
      # Core system libraries
      - libc6
      - libstdc++6
      - libaio1t64
      # Ubuntu/Kubuntu metapackages
      - ubuntu-minimal
      - ubuntu-standard
      - kubuntu-desktop
      # Linux kernel
      - linux-generic
      - linux-image-generic
      - linux-headers-generic
      # BIOS/Legacy bootloader
      - grub-common
      - grub-pc
      - grub-pc-bin
      - grub2-common
      # EFI/UEFI bootloader
      - efibootmgr
      - grub-efi-amd64-signed
      - grub-efi-amd64-bin
      - grub-efi-amd64-unsigned
      - grub-gfxpayload-lists
      - shim-signed
      - mokutil
      # Disk and filesystem management
      - mount
      - fdisk
      - btrfs-progs
      - xfsprogs
      # LVM and device mapper
      - lvm2
      - liblvm2cmd2.03
      - dmeventd
      - libdevmapper-event1.02.1
      - thin-provisioning-tools
      # Hardware management
      - udev
      # System communication and networking
      - dbus
      - networkmanager
      - network-manager
      # Display server and login manager
      - sddm
      - xorg
      - xserver-xorg
      - wayland
      # KDE/Plasma desktop components
      - baloo-kf5
      - libappstreamqt5-3
      - kde-config-fcitx5
      # Password quality and security libraries
      - libpwquality1
      - libpwquality-common
      - libcrack2
      - cracklib-runtime
      # Miscellaneous libraries and utilities
      - libyaml-cpp0.8
      - libwebkit2gtk-4.1-0
  tasks:
    - name: Gathering Package Facts
      ansible.builtin.package_facts: { manager: apt }

    # =========================================================================
    # REPOSITORY CONFIGURATION
    # =========================================================================
    - name: Enable the Ubuntu restricted repository
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} restricted"
        state: present

    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Tailscale
    - name: Download Tailscale GPG key
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/plucky.noarmor.gpg > /usr/share/keyrings/tailscale-archive-keyring.gpg
      args: { creates: /usr/share/keyrings/tailscale-archive-keyring.gpg }

    - name: Add Tailscale repository
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/plucky.tailscale-keyring.list > /etc/apt/sources.list.d/tailscale.list
      args: { creates: /etc/apt/sources.list.d/tailscale.list }

    # Brave Browser
    - name: Get Brave GPG key
      ansible.builtin.shell: >
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg
        https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      args: { creates: /usr/share/keyrings/brave-browser-archive-keyring.gpg }

    - name: Add Brave browser release sources
      ansible.builtin.shell: >
        curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources
        https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
      args: { creates: /etc/apt/sources.list.d/brave-browser-release.sources }

    # VS Code (Microsoft)
    - name: Download Microsoft GPG key
      ansible.builtin.shell: >
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
      args: { creates: /tmp/packages.microsoft.gpg }

    - name: Install Microsoft GPG key
      ansible.builtin.shell: >
        install -D -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
      args: { creates: /etc/apt/keyrings/packages.microsoft.gpg }

    - name: Add VS Code repository
      ansible.builtin.shell: >
        echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
      args: { creates: /etc/apt/sources.list.d/vscode.list }

    # 1Password
    - name: Download 1Password GPG key for APT
      ansible.builtin.shell: >
        curl -sS https://downloads.1password.com/linux/keys/1password.asc |
        gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
      args: { creates: /usr/share/keyrings/1password-archive-keyring.gpg }

    - name: Add 1Password repository
      ansible.builtin.shell: >
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' > /etc/apt/sources.list.d/1password.list
      args: { creates: /etc/apt/sources.list.d/1password.list }

    - name: Setup 1Password debsig verification
      ansible.builtin.shell: |
        mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol > /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      args: { creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg }

    # Docker
    - name: Download Docker GPG key
      ansible.builtin.shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args: { creates: /etc/apt/keyrings/docker.asc }

    - name: Set Docker GPG key permissions
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" > /etc/apt/sources.list.d/docker.list
      args: { creates: /etc/apt/sources.list.d/docker.list }

    # Warp Terminal
    - name: Download Warp GPG key
      ansible.builtin.shell: >
        wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > /tmp/warpdotdev.gpg
      args: { creates: /tmp/warpdotdev.gpg }

    - name: Install Warp GPG key
      ansible.builtin.shell: >
        install -D -o root -g root -m 644 /tmp/warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
      args: { creates: /etc/apt/keyrings/warpdotdev.gpg }

    - name: Add Warp repository
      ansible.builtin.shell: >
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list
      args: { creates: /etc/apt/sources.list.d/warpdotdev.list }

    # =========================================================================
    # APT PACKAGE INSTALLATION (single step after all repos configured)
    # =========================================================================
    - name: Install all managed APT packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ managed_apt_packages }}"
        state: present

    - name: Upgrade APT packages
      ansible.builtin.apt: { upgrade: full }

    # =========================================================================
    # FLATPAK INSTALLATION
    # =========================================================================
    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ managed_flatpaks }}"
        state: latest

    - name: Configure pipx for user
      become: false
      ansible.builtin.command: pipx ensurepath

      register: pipx_ensurepath
      changed_when: false

    - name: Install pipx packages
      become: false
      vars:
        pipx_packages:
          - poetry
          - uv
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items: "{{ pipx_packages }}"

    - name: Enable service Syncthing
      become: false
      ansible.builtin.systemd_service:
        name: syncthing.service
        enabled: true
        state: started
        scope: user

    - name: Configure global Git config
      become: false
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - { name: init.defaultBranch, value: "master" }
        - { name: user.name, value: "Iaroslav Postovalov" }
        - { name: user.email, value: "postovalovya@gmail.com" }
        - { name: core.autocrlf, value: "input" }
        - name: user.signingkey
          value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhrNPHMWPV7gGuPheIX4POXrlPNNL2h/KMAJsAuSA0W"
        - { name: gpg.format, value: "ssh" }
        - { name: gpg.ssh.program, value: "/opt/1Password/op-ssh-sign" }
        - { name: commit.gpgsign, value: "true" }
      failed_when: "'/opt/1Password/op-ssh-sign' is not file"

    # =========================================================================
    # CLEANUP: Remove unmanaged Flatpak applications
    # =========================================================================
    - name: Gather installed Flatpak applications
      ansible.builtin.command: flatpak list --app --columns=application
      register: installed_flatpaks_raw
      changed_when: false
      failed_when: false

    - name: Prune unmanaged Flatpak applications
      vars:
        installed_flatpaks: "{{ installed_flatpaks_raw.stdout_lines | default([]) }}"
        unmanaged_flatpaks: "{{ installed_flatpaks | difference(managed_flatpaks) }}"
      when: unmanaged_flatpaks | length > 0
      block:
        - name: Confirm Flatpak pruning
          ansible.builtin.pause:
            prompt: |
              The following unmanaged Flatpak applications will be removed:
              {{ unmanaged_flatpaks | to_nice_yaml }}
              Press Enter to continue, or Ctrl+C and then 'A' to abort.

        - name: Remove unmanaged Flatpak applications
          community.general.flatpak:
            name: "{{ item }}"
            state: absent
          loop: "{{ unmanaged_flatpaks }}"

    # =========================================================================
    # CLEANUP: Remove unmanaged APT packages
    # =========================================================================
    - name: Gather APT package information
      block:
        - name: Get manually installed packages (not auto-installed as dependencies)
          ansible.builtin.shell: |
            apt-mark showmanual | sort
          register: manually_installed_raw
          changed_when: false

        - name: Get all dependencies of managed packages
          ansible.builtin.shell: |
            apt-cache depends --recurse --no-recommends --no-suggests \
              --no-conflicts --no-breaks --no-replaces --no-enhances \
              {{ managed_apt_packages | join(' ') }} 2>/dev/null | \
              grep -E '^\w' | sort -u || true
          register: managed_deps_raw
          changed_when: false
          failed_when: false

        - name: Get all essential and required packages
          ansible.builtin.shell: |
            dpkg-query -W -f='${Package} ${Essential} ${Priority}\n' | \
              awk '($2 == "yes" || $3 == "required" || $3 == "important") {print $1}' | sort -u
          register: essential_packages_raw
          changed_when: false

    - name: Compute and prune unmanaged APT packages
      vars:
        manually_installed: "{{ manually_installed_raw.stdout_lines | default([]) }}"
        managed_deps: "{{ managed_deps_raw.stdout_lines | default([]) }}"
        essential_packages: "{{ essential_packages_raw.stdout_lines | default([]) }}"
        all_protected: "{{ (protected_apt_packages + managed_apt_packages + managed_deps + essential_packages) | unique }}"
        unmanaged_apt: "{{ manually_installed | difference(all_protected) }}"
      when: unmanaged_apt | length > 0
      block:
        - name: Confirm APT package pruning
          ansible.builtin.pause:
            prompt: |
              ⚠️  WARNING: You are about to remove APT packages.

              The following will be purged:
              {{ unmanaged_apt | to_nice_yaml }}

              Press Enter to continue, or Ctrl+C and then 'A' to abort.

        # APT handles dependency ordering automatically when given the full list.
        - name: Purge unmanaged APT packages with autoremove
          ansible.builtin.apt:
            name: "{{ unmanaged_apt }}"
            state: absent
            purge: true
            autoremove: true
          register: apt_purge_result

        - name: Run additional autoremove to clean orphaned dependencies
          ansible.builtin.apt:
            autoremove: true
            purge: true
