---
- name: Ansible for macOS with Homebrew
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
    homebrew_packages:
      - ansible
      - ansible-lint
      - wget
      - tree
      - git
      - postgresql@14
      - curl
      - fastfetch
      - gource
      - node
      - pnpm
      - ffmpeg
      - uv
      - tmux
      - gh # GitHub
      - ripgrep
      - glab # GitLab
      - deno
    homebrew_protected:
      - mvnd@1
      - hue-manager
    homebrew_cask_apps:
      - brave-browser
      - 1password
      - 1password-cli
      - vlc
      - gimp
      - syncthing-app
      - qdirstat
      - anki
      - obsidian
      - tailscale-app
      - font-jetbrains-mono
      - balenaetcher
      - jetbrains-toolbox
      - alt-tab
      - zulip
      - docker-desktop
      - claude
      - slack
      - arc
      - flux-app
      - philips-hue-sync
      - claude-code
      - zed
      - codex
      - monitorcontrol
  tasks:
    - name: Update Homebrew
      community.general.homebrew: { update_homebrew: true }

    - name: Tap mvndaemon/homebrew-mvnd
      community.general.homebrew_tap:
        name: mvndaemon/homebrew-mvnd
        state: present

    - name: Get mvnd dependencies
      ansible.builtin.command: brew deps mvndaemon/mvnd/mvnd@1
      register: mvnd_deps
      changed_when: false
      failed_when: false

    - name: Install mvnd dependencies except openjdk
      community.general.homebrew:
        name: "{{ mvnd_deps.stdout_lines | reject('match', '^openjdk(@.*)?$') | list }}"
        state: present
      when: mvnd_deps.stdout_lines | length > 0

    - name: Install mvnd with ignore-dependencies for openjdk
      community.general.homebrew:
        name: mvndaemon/mvnd/mvnd@1
        state: present
        install_options: ignore-dependencies

    - name: Create symlink for mvnd binary
      ansible.builtin.file:
        src: /opt/homebrew/opt/mvnd@1/bin/mvnd
        dest: /opt/homebrew/bin/mvnd
        state: link
        force: true

    - name: Create symlink for mvn to mvnd
      ansible.builtin.file:
        src: /opt/homebrew/bin/mvnd
        dest: /opt/homebrew/bin/mvn
        state: link
        force: true

    - name: Install Homebrew formula packages
      community.general.homebrew:
        name: "{{ homebrew_packages }}"
        state: latest

    - name: Tap commandertvis/hue-manager (private)
      community.general.homebrew_tap:
        name: commandertvis/hue-manager
        url: git@github.com:CommanderTvis/hue-manager.git
        state: present
      register: hue_tap
      failed_when: false

    - name: Install hue-manager cask
      community.general.homebrew_cask:
        name: hue-manager
        state: latest
        accept_external_apps: true
        sudo_password: "{{ ansible_become_password }}"
      when: hue_tap is succeeded
      register: hue_install
      failed_when: false

    - name: Warn if hue-manager tap/install failed
      ansible.builtin.debug:
        msg: "hue-manager skipped — tap failed (no SSH access to private repo?)"
      when: hue_tap is failed

    - name: Warn if hue-manager install failed
      ansible.builtin.debug:
        msg: "hue-manager install failed — {{ hue_install.msg | default('unknown error') }}"
      when: hue_tap is succeeded and hue_install is failed

    - name: Install Homebrew cask applications
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_apps }}"
        state: latest
        accept_external_apps: true
        sudo_password: "{{ ansible_become_password }}"

    - name: Install yarn globally with npm
      community.general.npm:
        name: yarn
        global: true
        state: latest

    - name: Set DNS to 1.1.1.1 on all network services
      ansible.builtin.shell: |
        while IFS= read -r svc; do
          networksetup -setdnsservers "$svc" 1.1.1.1 1.0.0.1
        done < <(networksetup -listallnetworkservices | tail -n +2)
      become: true
      changed_when: false

    - name: Configure global Git config
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - { name: init.defaultBranch, value: master }
        - { name: user.name, value: "Iaroslav Postovalov" }
        - { name: user.email, value: "postovalovya@gmail.com" }
        - { name: core.autocrlf, value: input }
        - name: user.signingkey
          value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhrNPHMWPV7gGuPheIX4POXrlPNNL2h/KMAJsAuSA0W"
        - { name: gpg.format, value: "ssh" }
        - {
            name: gpg.ssh.program,
            value: "/Applications/1Password.app/Contents/MacOS/op-ssh-sign",
          }
        - { name: commit.gpgsign, value: "true" }

    - name: Gather installed packages and dependencies
      block:
        - name: List installed formulae
          ansible.builtin.command: brew list --formula -1
          register: installed_formulae
          changed_when: false
        - name: List installed casks
          ansible.builtin.command: brew list --cask -1
          register: installed_casks
          changed_when: false
        - name: Gather managed dependencies
          ansible.builtin.command: |
            brew deps --union --include-build --include-optional {{ homebrew_packages | join(' ') }}
          register: managed_deps
          changed_when: false
          failed_when: false

    - name: Prune unmanaged packages
      vars:
        installed: "{{ installed_formulae.stdout_lines + installed_casks.stdout_lines }}"
        managed: "{{ homebrew_packages + homebrew_cask_apps + homebrew_protected }}"
        dependencies: "{{ managed_deps.stdout_lines | default([]) }}"
        unmanaged: "{{ installed | difference(managed + dependencies) }}"
      when: unmanaged is defined and unmanaged | length > 0
      block:
        - name: Confirm pruning
          ansible.builtin.pause:
            prompt: |
              The following unmanaged packages will be pruned:
              {{ unmanaged | to_nice_yaml }}
              Press Enter to continue, or Ctrl+C and then 'A' to abort.

        - name: Remove packages with dependencies
          ansible.builtin.shell: |
            for pkg in {{ unmanaged | join(' ') }}; do
              if brew list --formula | grep -q "^$pkg$"; then
                # Check if this package has dependents in our unmanaged list
                dependents=$(brew uses --installed --recursive $pkg 2>/dev/null | grep -E '^({{ unmanaged | join('|') }})$' | wc -l || echo 0)
                if [ "$dependents" -gt 0 ]; then
                  echo "Skipping $pkg - has dependents"
                else
                  echo "Removing $pkg - no dependents in unmanaged list"
                  brew uninstall $pkg 2>/dev/null || echo "Failed to remove $pkg"
                fi
              elif brew list --cask | grep -q "^$pkg$"; then
                echo "Removing cask $pkg"
                /usr/bin/expect <<EOF
            spawn brew uninstall --cask --force $pkg
            expect {
              "Password:" {
                send "{{ ansible_become_password }}\r"
                exp_continue
              }
              eof
            }
            EOF
              fi
            done
          register: first_pass_removal
          changed_when: "'Removing' in first_pass_removal.stdout"
          no_log: true

        - name: Remove remaining dependencies with force flag
          ansible.builtin.shell: |
            for pkg in {{ unmanaged | join(' ') }}; do
              if brew list --formula | grep -q "^$pkg$" 2>/dev/null; then
                echo "Force removing remaining package: $pkg"
                brew uninstall --ignore-dependencies $pkg 2>/dev/null || echo "Failed to force remove $pkg"
              fi
            done
          register: second_pass_removal
          changed_when: "'Force removing' in second_pass_removal.stdout"
